### ISSUE TITLE
Not working on Google Chrome

### ISSUE THREAD

**Issue by Nogll** [JustKappaMan/VK-Video-Downloader#1]
Не работает на Google Chrome, проблему решил добавлением вызова main() в начале скрипта.

**Comment by JustKappaMan** [comment]
> Не работает на Google Chrome, проблему решил добавлением вызова main() в начале скрипта.

Только что проверил, всё работает (Google Chrome 112.0.5615.138).

Чтобы избежать некоторых проблем функция `main` вызывается лишь при соблюдении ряда условий:
* Вы находитесь на странице с видео
* На странице отрисовался видеоплеер
* На странице ещё не отрисовался блок с ссылками для скачивания.

Можете предоставить более подробные сведения об ошибке?

**Comment by Nogll** [comment]
Google Chrome 112.0.5615.138, при открытии сайта с видео m.vk.com блок с ссылками не появляется, если добавить принудительный вызов main(), то все работает хорошо. Может быть я как-то не правильно установил расширение?

**Comment by JustKappaMan** [comment]
> Google Chrome 112.0.5615.138, при открытии сайта с видео m.vk.com блок с ссылками не появляется, если добавить принудительный вызов main(), то все работает хорошо. Может быть я как-то не правильно установил расширение?

Да вроде бы невозможно его неправильно установить. Интересно. А в консоли никакие ошибки связанные с расширением не появляются? Попробуйте открыть консоль и перезагрузить страницу с видео.

**Comment by Nogll** [comment]
Я заметил, что если видео прислал человек в личные сообщения, то расширение не хочет отображать ссылки, а для видео, которое в сообществе все работает. Однако, если до этого открыть видео из какого-нибудь сообщества, то ссылки начинают отображаться и в личных сообщения, в пределах этой вкладки браузера. В новой вкладке опять не будут отображаться ссылки, пока не открыть видео из какого-нибудь сообщества.

**Comment by JustKappaMan** [comment]
> Я заметил, что если видео прислал человек в личные сообщения, то расширение не хочет отображать ссылки, а для видео, которое в сообществе все работает. Однако, если до этого открыть видео из какого-нибудь сообщества, то ссылки начинают отображаться и в личных сообщения, в пределах этой вкладки браузера. В новой вкладке опять не будут отображаться ссылки, пока не открыть видео из какого-нибудь сообщества.

Спасибо за информацию. На видео в личных сообщениях не тестировал. Погляжу в чём проблема и постараюсь исправить в ближайшее время.

**Comment by JustKappaMan** [comment]
@Nogll скачайте новую версию, проверьте, теперь всё должно работать как полагается.

**Comment by Nogll** [comment]
Теперь все работает хорошо. Большое спасибо!

**Comment by JustKappaMan** [comment]
> Теперь все работает хорошо. Большое спасибо!

Вам спасибо за репорт :)
