### ISSUE TITLE
Doesn't work 2024.6.2

### ISSUE THREAD

**Issue by youngbeauty** [JustKappaMan/VK-Video-Downloader#10]
Recently the programme doesn't work,there is no download option under the video.

**Comment by JustKappaMan** [comment]
@youngbeauty hi. Guys from @VKCOM made a tiny re-desing. Again. That's why the links weren't shown. Fixed. Just download and install the latest version of the extension. Thanks for the report.

P.S. The links are now shown in the bottom left corner of the browser window :slightly_smiling_face:
