### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by michailVs** [JustKappaMan/VK-Video-Downloader#11]
![изображение_2024-06-05_212532366](https://github.com/JustKappaMan/VK-Video-Downloader/assets/106434961/fe090951-e6ff-4ea5-83d1-f76040b69436)

**Comment by michailVs** [comment]
desktop-injection:41 - document.querySelector('div#mv_goods_recognition').after(panel);
desctop:57 - document.querySelector('div.mv_goods_recognition').after(panel);

**Comment by JustKappaMan** [comment]
@michailVs привет. Ребята из @VKCOM сделали небольшой редизайн. Снова. Поэтому ссылки не отображались. Пофиксил. Можешь скачать и установить последнюю версию расширения. Спасибо за информацию.

P.S. Теперь ссылки отображаются в левом нижнем углу страницы :slightly_smiling_face:
