### ISSUE TITLE
Не работает на обновленом вк видео!

### ISSUE THREAD

**Issue by Dionis94** [JustKappaMan/VK-Video-Downloader#14]
Здравствуйте! Вк видео обновился и скачивание пропало!!!
![Uploading Безымянный.png…]()

**Comment by JustKappaMan** [comment]
@Dionis94 приветствую. У меня, пока что, всё работает. Вероятно постепенно раскатывают обновление.

Быть может дело и вовсе не в обновлении. Есть ссылка на конкретную страницу где не работает расширение? :slightly_smiling_face: 

P.S. Приложенная картинка загружена как-то не так.

**Comment by Dionis94** [comment]
Здравствуйте. Я проверил и получается, что приложение работает в месенджере, а в вк-видео нет. Вот фото надеюсь в этот раз загрузятся. 
![Безымяннттттый](https://github.com/user-attachments/assets/1f1d3815-f133-4d0c-955c-d8f462b64873)
![ыыыыы](https://github.com/user-attachments/assets/321e516d-f3b0-49d4-942c-4ec4a1506d9a)

**Comment by JustKappaMan** [comment]
@Dionis94 спасибо за информацию, глянул. Имеем сразу 2 проблемы:

- Адрес "VK Видео" изменился на vkvideo.ru и скрипт просто не отрабатывает на нём
- Ребята из VK снова перелопатили плеер -> изменились JS объекты

Сделать 1-ую правку мне не составит труда, но без 2-ой это бессмысленно. А на 2-ую у меня сейчас нет времени.

Нужно:
- Открыть любое видео на vkvideo.ru
- Открыть JS консоль
- Ввести `window`
- **Среди тысяч вложенных объектов** найти ссылки на видео

После этого поправить скрипт не составит труда.

**Comment by SpukiBugi** [comment]
@JustKappaMan 
Ссылки теперь лежат в supportedWindow.cur.videoInlinePlayer.vars.url720

**Comment by JustKappaMan** [comment]
@SpukiBugi благодарю, упомянул тебя в README :slightly_smiling_face:

@Dionis94 @potap1978 @ORANG4 @youngbeauty протестировал новую версию в Chrome и Firefox (Tampermonkey). У меня всё работает. Можете обновляться.

**Comment by youngbeauty** [comment]
@JustKappaMan  @SpukiBugi  Man! You  guys are the real hero! Thanks a lot!
