### ISSUE TITLE
Download links don't appear

### ISSUE THREAD

**Issue by Manssizz** [JustKappaMan/VK-Video-Downloader#2]
### Environment
- Firefox
- User Agent Switcher
- Violetmonkey

Hello... there is bug? or this script not working with violetmonkey?
![image](https://user-images.githubusercontent.com/23637327/235711779-94f2790b-3611-4dc8-b505-edbb8eca6008.png)

**Comment by JustKappaMan** [comment]
Hi. Haven't tested it on Violetmonkey. I'll try to check what the problem is tomorrow.

**Comment by JustKappaMan** [comment]
@Manssizz Check out the latest version. It should work properly now. It wasn't actually Violentmonkey's fault. Just a tiny bug.

Tested the extension on Tampermonkey, Greasemonkey and Violentmonkey. It now works for me on all of them. Fixed another bug on Greasemonkey btw.

Thanks for the report :)
