### ISSUE TITLE
Скрипт tampermonkey для десктопа не срабатывает в VK

### ISSUE THREAD

**Issue by VVSite** [JustKappaMan/VK-Video-Downloader#3]
На страница, вида **https://vk.com/video-9693056_456247324** скрипт не работает. Я нашел решение, надо всего лишь сделать проверку адреса: 
- в 30 строке: if ((location.search.includes('z=video') || location.search.includes('z=clip') **|| location.href.includes('video-')**) && !checkerHasBeenCalled) {
- в 94 строке: if (location.search.includes('z=video') **|| location.href.includes('video-')**) {

Скорее всего такая же проблема есть и в мобильной версии скрипта.

**Comment by JustKappaMan** [comment]
> На страница, вида **https://vk.com/video-9693056_456247324** скрипт не работает.

Спасибо за репорт. Сегодня исправлю, как только свет дадут :)

На Хабре в комментах писали, что при открывании видео в новой вкладке скрипт тоже не срабатывает. Сейчас глянул - проблема та же самая что и здесь. По разному выглядят URL при переходе на другое видео в текущей вкладке и при открытии его в новой вкладке.

**Comment by JustKappaMan** [comment]
@VVSite пофиксил в 1.1.6. Теперь всё работает корректно и на видео, и на клипах, и в десктопной, и в мобильной версиях.

**Comment by VVSite** [comment]
👍
