### ISSUE TITLE
Не встраиваются ссылки на страницу

### ISSUE THREAD

**Issue by WzorOn** [JustKappaMan/VK-Video-Downloader#6]
Привет.
Не мог бы глянуть почему в desktop версия для firefox перестала работать, не встраивает ссылки на страницу как минимум.
Мобильная версии в FF работает.

**Comment by JustKappaMan** [comment]
@WzorOn привет, у меня на **Firefox 122.0.1** и **Tampermonkey 5.0.1** всё работает. А что ты используешь и каких версий? И может быть есть ссылка на конкретное проблемное видео?

**Comment by WzorOn** [comment]
@JustKappaMan Привет!
У меня FF 123, работать перестало на каком-то из билдов 122
![image](https://github.com/JustKappaMan/VK-Video-Downloader/assets/40578967/3ece6b1f-3e42-45f4-a860-4f383ece4015)
В мобильной версии все норм
![image](https://github.com/JustKappaMan/VK-Video-Downloader/assets/40578967/4b3ae8c4-a4c1-4cb3-8fe5-471d047185aa)

**Comment by JustKappaMan** [comment]
@WzorOn хм, даже не знаю в чём может быть проблема. Иногда @VKCOM проводит a/b тестирование и меняет всякое для части пользователей. Может в этом дело.

Подобное уже было когда я начинал разрабатывать расширение. Изменили архитектуру мобильного плеера, пришлось адаптироваться. Заметил это не сразу, так как не попал в тестовую группу.

Глянь консоль. Если там есть какие ошибки, то покажи пожалуйста.

**Comment by WzorOn** [comment]
@JustKappaMan Вот что в консоли
[console-export-2024-2-22_16-58-7.txt](https://github.com/JustKappaMan/VK-Video-Downloader/files/14374717/console-export-2024-2-22_16-58-7.txt)

**Comment by JustKappaMan** [comment]
@WzorOn спасибо. Разобрался в чём дело. Ссылки успешно достаются, проблема возникает при попытке их отобразить. 

У меня блок с лайком/репостом располагается между названием видео и автором. У тебя - справа от автора. Короче блока, на который я ориентируюсь при вставке ссылок, не существует в твоём случае.

![Screenshot from 2024-02-22 20-31-46](https://github.com/JustKappaMan/VK-Video-Downloader/assets/54501945/8b2101ad-e44c-4fec-9310-d4e4b538493c)

Это либо очередной редизайн @VKCOM для части пользователей, либо адаптивная вёрстка так себя ведёт на некоторых разрешениях экрана. Напиши какое у тебя **разрешение экрана**, пожалуйста. Погляжу что с этим можно сделать как будет время.

Временное решение - на странице видео в консоли пишешь `mvcur.player.vars.url`, она предложит продолжение в виде `mvcur.player.vars.url480`, `mvcur.player.vars.url720` и т.д. Выбираешь нужное, появляется ссылка.

Спасибо за баг-репорт :slightly_smiling_face:

**Comment by WzorOn** [comment]
@JustKappaMan Разрешение ПК с которого скидывал лог 1920*1080, на ноуте с MacOS 13.6.4 разрешение 1680*1050 отображается все одинакого на них.

P.S.
Блок куда должны были вставляться ссылки почему-то находится сейчас посредине+- видео плеера...
Но получилось самому найти куда воткнуть ссылки, немного кривовато, но мне пойдет))
![image](https://github.com/JustKappaMan/VK-Video-Downloader/assets/40578967/9a06f8a0-f5d2-49ab-9488-7b02a9f2425d)
![image](https://github.com/JustKappaMan/VK-Video-Downloader/assets/40578967/998d3187-2ebd-41a1-a7cc-738d07b45810)
Спасибо за помощь!
