### ISSUE TITLE
Нет ссылок для больших видео, а может и вообще нет

### ISSUE THREAD

**Issue by u33aga** [JustKappaMan/VK-Video-Downloader#7]
![image](https://github.com/JustKappaMan/VK-Video-Downloader/assets/372634/d36b2efa-8dc8-4c3d-8231-bf54664bf2c9)

**Comment by JustKappaMan** [comment]
@u33aga привет, нужны подробности.

Запускаешь расширение напрямую или через какую-то monkey? Какой браузер? Какой версии? Какая конкретно monkey и какой версии если используешь? Что по ошибкам в консоли браузера на странице видео? Если возможно, то дай ссылку на проблемное видео.

**Comment by u33aga** [comment]
Не могу дать ссылку там ограниченный доступ

Последний:

Гугл
Яндекс

Violent макака

Видео 1-2 часа


Нашел другое решение

Не сразу тоже скачалось

Видимо из кеша тянет



сб, 24 февр. 2024 г., 19:40 Kirill Volozhanin ***@***.***>:
