### ISSUE TITLE
ошибка сети

### ISSUE THREAD

**Issue by BlindLesbianInAFishStore** [JustKappaMan/VK-Video-Downloader#9]
сначала скорость на 795мб ролик был 4мб/с. потом скорость падает до 250кб сек через секунд 10, а под конец зависло и ошибка сети
как мне фильмы для потомков архивировать то

**Comment by JustKappaMan** [comment]
@BlindLesbianInAFishStore привет, к сожалению это ограничение со стороны VK, как понимаю, связанное с их CDN. Частенько при скачивании больших файлов действительно может сильно проседать скорость.

**Comment by BlindLesbianInAFishStore** [comment]
ладно, дух машины смог мне скачать фильм при повторной попытке. Спокойной ночи
